### ISSUE TITLE
BitPoolMiner stuck trying to open EWBF files. 

### ISSUE THREAD

**Issue by bagleyed2** [BitPoolMining/BitPoolMiner#35]
"Stop" doesn't work and app recycles endlessly trying to open EWBF. Task manager is the only way to close the miner app. When reopened the error continues. Since there is no easy way to uninstall BitPoolMiner and reinstall, your suggestions are appreciated.

**Comment by saltyminer** [comment]
Will let me know what version number you are on and which coin you are mining?  You can find the version number on the footer bar.  We recently put in a new version of EWBF in the most recent release yesterday.  

Also, BPM should auto detect newer versions and give the option to update when you close/reopen it.
